### ISSUE TITLE
First page is empty at startup for M5Stack CoreS3 ESP32S3

### ISSUE THREAD

**Issue by lboue** [m5stack/CoreS3-Box#1]
## Issue: First page is empty at startup for M5Stack CoreS3 ESP32S3

Hello,

It noticed first page is empty for M5Stack CoreS3 ESP32S3. What is the purpose of having an empty page?
![IMG-3153](https://github.com/m5stack/CoreS3-Box/assets/938089/44a2ce44-8932-4c78-bb29-ed234db8b390)

### Steps to reproduce

I flashed CoreS3-Box demo for M5 Burner:  
![image](https://github.com/espressif/esp-box/assets/938089/2cca6028-2051-4107-9ca3-48d832b47e53)

### Expected behavior
This page should show "Touch to return"

**Comment by imliubo** [comment]
Looks the problem is [here](https://github.com/m5stack/CoreS3-Box/blob/dev-cores3/examples/factory_demo/main/gui/ui_hint.c#L120), I will fix this.

**Comment by lboue** [comment]
Thanks @imliubo

**Comment by IcingTomato** [comment]
![image](https://github.com/m5stack/CoreS3-Box/assets/24474531/fa031a25-f175-43b6-ac31-73cda0a1f709)
Fixed! Please check.
We will push the updated flash file after #3 fix.
