### ISSUE TITLE
Media Player: The volume is not correctly managed in the "Media" section

### ISSUE THREAD

**Issue by lboue** [m5stack/CoreS3-Box#2]
## Issue: The volume is not correctly managed in the "Media" section.
There is still sound coming out of the speaker when volume it set to 0.
![IMG-3162345333](https://github.com/m5stack/CoreS3-Box/assets/938089/f2570fbd-933d-40eb-ae2e-f249f3cc06d5)

### Steps to reproduce
I flashed CoreS3-Box demo for M5 Burner
Start to play a file in "Media" section

### Expected behavior
This speaker should be muted when volume set to 0.

**Comment by imliubo** [comment]
Sorry, the volume function is not implemented yet, I will fix this ASAP.

[volume function](https://github.com/m5stack/CoreS3-Box/blob/dev-cores3/components/bsp/src/boards/m5stack_cores3.c#L189-L197)

**Comment by IcingTomato** [comment]
Fixed! And we will push the flash images on M5Burner later.
